[package]
edition = "2021"
name = "plasma-amm-state"
version = "0.1.0"

[features]
borsh = ["dep:borsh"]

[dependencies]
borsh = { version = "0.10.0", optional = true }
bs58 = { workspace = true }
bytemuck = { workspace = true }
fixed = "1.27.0"

[dev-dependencies]
rand = "0.7.0"
